spring.application.name=demo
spring.datasource.url=jdbc:mysql://172.17.0.1:3306/db_portofolio
spring.datasource.username=haris_user
spring.datasource.password=SERVERSANDGEN
#spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8001

# JPA Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.operations-sorter=alpha
server.forward-headers-strategy=framework
springdoc.server-url=https://be-portofolio.serversandgen.web.id
